# Generated by Django 5.0.2 on 2024-02-20 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
