# Generated by Django 5.0.2 on 2024-02-22 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='variations',
            new_name='variation',
        ),
    ]
